version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    tty: true
    stdin_open: true
